name: CI/CD for NestJS

on:
 push:
    branches:
      - main
      - dev
      - staging
 pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
 lint:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: npm install

        - name: Lint
          run: npm run lint

 test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: npm install

        - name: Test
          run: npm test


 build:
    runs-on: ubuntu-latest


    strategy:
        matrix:
            node-version: [16.x, 18.x]

    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{matrix.node-version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.node-version}}


        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build --if-present


